CREATE TABLE bank_branches (
    id SERIAL PRIMARY KEY,
    bank_id INTEGER NOT NULL REFERENCES banks(id),
    name VARCHAR(100) NOT NULL,
    street TEXT,
    city TEXT NOT NULL,
    state VARCHAR(50),
    postal_code VARCHAR(20),
    country_id INTEGER NOT NULL REFERENCES countries(id),
    swift VARCHAR(11),
    description TEXT
);

INSERT INTO bank_branches (bank_id,name,city,country_id,swift) VALUES
  (1,'BANK OF GUYANA, GEORGETOWN','GEORGETOWN',1,'GUBAGYGG'),
  (2,'BANK OF NOVA SCOTIA,THE, GEORGETOWN','GEORGETOWN',1,'NOSCGYGE'),
  (3,'CITIZENS BANK GUYANA INC, GEORGETOWN','GEORGETOWN',1,'CBGIGYGG'),
  (4,'DEMERARA BANK LIMITED, GEORGETOWN','GEORGETOWN',1,'DMBKGYGT'),
  (5,'(MAIN BRANCH)','GEORGETOWN',1,'GUTIGYGE'),
  (6,'REPUBLIC BANK (GUYANA) LIMITED, GEORGETOWN','GEORGETOWN',1,'RBGLGYGG');
