CREATE TABLE banks (
    id SERIAL PRIMARY KEY,
    record_group INTEGER NOT NULL,
    is_current BOOLEAN NOT NULL DEFAULT TRUE,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO banks (record_group,name) VALUES
  (1,'BANK OF GUYANA'),
  (2,'BANK OF NOVA SCOTIA,THE'),
  (3,'CITIZENS BANK GUYANA INC'),
  (4,'DEMERARA BANK LIMITED'),
  (5,'GUYANA BANK FOR TRADE AND INDUSTRY LTD.'),
  (6,'REPUBLIC BANK (GUYANA) LIMITED');
